goog.setCssNameMapping({
  "social": "a",
  "logoContainer": "b",
  "socialContainer": "c",
  "facebook": "d",
  "twitter": "e",
  "youtube": "f",
  "newgrounds": "g",
  "tumblr": "h",
  "pageNavigator": "i",
  "copyright": "j",
  "comicContentContainer": "k",
  "comicNavigation": "l",
  "navIcon": "m",
  "navFirst": "n",
  "navPrevious": "o",
  "navRandom": "p",
  "navNext": "q",
  "navLatest": "r",
  "deactive": "s"
});
